from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Paquetes
    url(r'^paquetes$','pyllik.views.paqueteList', name='paqueteList'),
    url(r'^paquetes/rendimiento$','pyllik.views.paquetesRendimiento', name='paquetesRendimiento'),
    url(r'^paquete/detail/(?P<id>\d+)$','pyllik.views.paqueteDetail', name='paqueteDetail'),
    url(r'^paquete/edit/(?P<id>\d+)$','pyllik.views.paqueteEdit', name='paqueteEdit'),
    url(r'^paquete/add/$','pyllik.views.paqueteAdd', name='paqueteAdd'),
    # Empresa
    url(r'^$','pyllik.views.index', name='index'),
    url(r'^information/$','pyllik.views.empresaDetail', name='empresaDetail'),
    url(r'^edit/$','pyllik.views.empresaEdit', name='empresaEdit'),
    url(r'^edit/paypal_account$','pyllik.views.paypal_account', name='paypal_account'),
    url(r'^edit/logo$','pyllik.views.logo', name='logo'),
    # Reservas
    url(r'^reservas$','pyllik.views.reservaList', name='reservaList'),
    url(r'^reservas/confirmadas$','pyllik.views.reservaConfirmadas', name='reservaConfirmadas'),
    #url(r'^reservas/analytics$','pyllik.views.reservaAnalytics', name='reservaAnalytics'),
    url(r'^reserva/detail/(?P<id>\d+)$','pyllik.views.reservaDetail', name='reservaDetail'),
    url(r'^reserva/(?P<id>\d+)/add/pasajeros$','pyllik.views.reservaAddPasajero', name='reservaAddPasajero'),
    url(r'^reserva/edit/estado/(?P<id>\d+)$','pyllik.views.reservaEstado', name='reservaEstado'),
    #rl(r'^reserva/edit/(?P<id>\d+)$','pyllik.views.reservaEdit', name='reservaEdit'),
    url(r'^reserva/paquete/(?P<sku>\w{7})$','pyllik.views.reservaPaquete', name='reservaPaquete'),
    url(r'^pagos$','pyllik.views.pagos', name='pagos'),
    # Pasajeros
    url(r'^pasajeros$','pyllik.views.pasajeros', name='pasajeros'),
    url(r'^pasajero/add$','pyllik.views.pasajeroAdd', name='pasajeroAdd'),
    url(r'^pasajero/detail/(?P<id>\d+)$','pyllik.views.pasajeroDetail', name='pasajeroDetail'),
    url(r'^pasajero/edit/(?P<id>\d+)$','pyllik.views.pasajeroEdit', name='pasajeroEdit'),
    # Clientes
    url(r'^clientes$','pyllik.views.clientes', name='clientes'),
    url(r'^cliente/add/$','pyllik.views.clienteAdd', name='clienteAdd'),
    url(r'^cliente/detail/(?P<id>\d+)$','pyllik.views.clienteDetail', name='clienteDetail'),
    url(r'^cliente/edit/(?P<id>\d+)$','pyllik.views.clienteEdit', name='clienteEdit'),
    # Clientes
    url(r'^trabajadores$','pyllik.views.trabajadores', name='trabajadores'),
    url(r'^trabajador/add/$','pyllik.views.trabajadorAdd', name='trabajadorAdd'),
    url(r'^trabajador/detail/(?P<id>\d+)$','pyllik.views.trabajadorDetail', name='trabajadorDetail'),
    url(r'^trabajador/edit/(?P<id>\d+)$','pyllik.views.trabajadorEdit', name='trabajadorEdit'),
)
